version: '3.7'

services:
  mysql:
    image: mysql
    container_name: sales-app-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network
    ports:
      - "3306:3306"
    restart: always

  frontend:
    container_name: sales-app-frontend
    hostname: app
    build:
      context: ./app-sales-frontend
    ports:
      - "8081:8080"
    restart: always

  app:
    container_name: sales-app-backend
    hostname: app
    build:
      context: ./
    environment:
      - DB_HOST=sales-app-mysql
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - "8080:8080"
    command: "java -jar target/app-sales.jar"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge